// <auto-generated />
namespace Data_Access_Layer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class mgf : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mgf));
        
        string IMigrationMetadata.Id
        {
            get { return "202305061443447_mgf"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
